services:
  environment-server:
    build: infra/docker/ssh-server
    privileged: true
    environment:
      - GIT_NAME=Lorenzo Fornara
      - GIT_EMAIL=h4shell@gmail.com
    entrypoint: /usr/bin/entrypoint.sh
    container_name: environment-server
    hostname: "->env"
#    mem_limit: 16g
#    memswap_limit: 16g
    ports:
      - "2222:22"
      - "2223:20223"
    volumes:
      - home:/home
  
  wetty-env:
    image: wettyoss/wetty
    container_name: wetty-env
    ports:
      - "2220:20200"
    entrypoint: node /usr/src/app/build/main.js -p 20200 --ssh-host environment-server --ssh-user user
    environment:
      - SSH_HOST=environment-server
      - SSH_PORT=22
  
  cloudflare-env:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-env
    command: tunnel --url wetty-env:20200

#  firefox-env:
#    image: jlesage/firefox:latest
#    ports:
#      - "2221:5800"
#    container_name: firefox-env
#    volumes:
#      - firefox-env:/config

volumes:

  home:
    driver: local
#  firefox-env:
#    driver: local
