services:
  environment-server:
    build: infra/docker/ssh-server
    privileged: true
    environment:
      - GIT_NAME=Lorenzo Fornara
      - GIT_EMAIL=h4shell@gmail.com
    entrypoint: /usr/bin/entrypoint.sh
    container_name: environment-server
    hostname: "->env"
#    mem_limit: 16g
#    memswap_limit: 16g
    ports:
      - 2222:22
    volumes:
      - home:/home
volumes:

  home:
    driver: local
