#!/bin/bash
# Verifica che sia stato fornito almeno un parametro
if [ $# -eq 0 ]; then
    echo "Usage: $0 <port>"
    exit 1
fi
# Prendi la porta dal primo parametro
port=$1

echo "Select your tunnel:"
echo
select opt in "Cloudflare" "Localhost.run"; do
    case $opt in
        "Cloudflare")
            cloudflared --url localhost:${port}
            break
            ;;
        "Localhost.run")
            ssh -R 80:localhost:${port} nokey@localhost.run
            break
            ;;
        *) echo "Opzione non valida";;
    esac
done
