name: env

on:
  push:
    branches:
      - main

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - name: run env
        run: |
          git clone https://github.com/h4shell/environment.git
          cd environment
          cd ubuntu-environment
          docker compose up -d
          docker compose logs cloudflare-env | grep -o 'https://[^ ]*\.trycloudflare\.com' | head -n 1 | sed 's/$/\/wetty/'
          docker compose logs -f
          tail -f /dev/null
